version: "3.8"
services:
  next-prod:
    build:
      context: ./
      dockerfile: Dockerfile
    image: next-prod
    ports:
      - "80:3000"
    env_file:
      - .env.prod
    environment:
      NODE_ENV: production

  # next-nginx:
  #   build:
  #     context: ./
  #     dockerfile: Dockerfile
  #     target: nginx
  #   image: next-nginx
  #   ports:
  #     - 80:80
  #   depends_on:
  #     - next-prod
